c_compiler:                    # [win]
  - vs2019                     # [win]
cxx_compiler:                  # [win]
  - vs2019                     # [win]
abseil_cpp:                    # [win or osx]
 - '20211102.0'                # [win or osx]
