{% set version = "0.1.91" %}

package:
  name: sentencepiece
  version: {{ version }}

source:
  url: https://github.com/google/sentencepiece/archive/v{{ version }}.tar.gz
  sha256: acbc7ea12713cd2a8d64892f8d2033c7fd2bb4faecab39452496120ace9a4b1b

build:
  number: 5

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cmake
    - {{ compiler('cxx') }}
    - gperftools  # [unix]
    - make
    - pkg-config
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - sentencepiece
  requires:
    - pip
    - pytest
  source_files:
    - python/test
    - data
  commands:
    - pip check
    - spm_export_vocab --help  # [linux]
    - spm_normalize --help     # [linux]
    # upstream test suite expects to be run from PKG_ROOT/python
    - cd python && pytest test

about:
  home: "https://github.com/google/sentencepiece/"
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: "SentencePiece is an unsupervised text tokenizer and detokenizer mainly for Neural Network-based text generation systems where the vocabulary size is predetermined prior to the neural model training."

extra:
  recipe-maintainers:
    - setu4993
    - rluria14
    - ndmaxar
    - oblute
