{% set name = "sentencepiece" %}
{% set version = "0.1.95" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz  # [unix]
  url: https://github.com/google/{{ name }}/archive/v{{ version }}.tar.gz  # [win]
  sha256: 8dd6e3e110f4c3f85a46e4a2ae1b6f7cf020b907fab50eac22beccf1680e0ea5  # [unix]
  sha256: 1c0bd83e03f71a10fc934b7ce996e327488b838587f03159fd392c77c7701389  # [win]

build:
  number: 0
  skip: True  # [py<36]
  script: {{ PYTHON }} -m pip install . -vv  # [unix]

requirements:
  build:
    - cmake
    - {{ compiler('cxx') }}
    - gperftools  # [unix]
    - make
    - pkg-config
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - sentencepiece
  commands:
    - pip check
    - pytest test  # [unix]
    - pytest python/test  # [win]
  requires:
    - pip
    - pytest
  source_files:
    - test  # [unix]
    - python/test  # [win]

about:
  home: "https://github.com/google/sentencepiece/"
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: "SentencePiece is an unsupervised text tokenizer and detokenizer mainly for Neural Network-based text generation systems where the vocabulary size is predetermined prior to the neural model training."

extra:
  recipe-maintainers:
    - setu4993
    - rluria14
    - ndmaxar
    - oblute
