{% set name = "sentencepiece" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/google/{{ name }}/archive/{{ version }}.tar.gz
  sha256: db4352d4a46f1a40454c6b4f63370979ab27a895c5f319c61ff0dbaa1fd98ec9

build:
  number: 0
  skip: true  # [py<36 or win or osx]

requirements:
  build:
    - cmake
    - {{ compiler('cxx') }}
    - pkg-config
    - gperftools
    - make
  host:
    - pip
    - python
    - gperftools
  run:
    - python
    - gperftools

test:
  imports:
    - sentencepiece
  commands:
    - spm_export_vocab --help
    - spm_normalize --help

about:
  home: https://github.com/google/sentencepiece/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: SentencePiece is an unsupervised text tokenizer and detokenizer mainly for Neural Network-based text generation systems where the vocabulary size is predetermined prior to the neural model training.

extra:
  recipe-maintainers:
    - setu4993
