{% set name = "sentencepiece" %}
{% set version = "0.1.95" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/google/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 1c0bd83e03f71a10fc934b7ce996e327488b838587f03159fd392c77c7701389

build:
  number: 0
  skip: True  # [py<36 or osx]

requirements:
  build:
    - cmake
    - {{ compiler('cxx') }}
    - pkg-config
    - gperftools  # [unix]
    - make
  host:
    - pip
    - python
    - gperftools  # [unix]
  run:
    - python
    - gperftools  # [unix]

test:
  imports:
    - sentencepiece
  commands:
    - spm_export_vocab --help  # [unix]
    - spm_normalize --help  # [unix]

about:
  home: "https://github.com/google/sentencepiece/"
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: "SentencePiece is an unsupervised text tokenizer and detokenizer mainly for Neural Network-based text generation systems where the vocabulary size is predetermined prior to the neural model training."

extra:
  recipe-maintainers:
    - setu4993
    - rluria14
    - ndmaxar
    - oblute
