{% set name = "sentencepiece" %}
{% set version = "0.1.95" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8dd6e3e110f4c3f85a46e4a2ae1b6f7cf020b907fab50eac22beccf1680e0ea5

build:
  number: 0
  skip: True  # [py<36]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - cmake
    - {{ compiler('cxx') }}
    - make
  host:
    - pip
    - python
  run:
    - python
    - libgcc-ng
    - libstdcxx-ng

test:
  imports:
    - sentencepiece
  commands:
    - pip check
  requires:
    - pip

about:
  home: "https://github.com/google/sentencepiece/"
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: "SentencePiece is an unsupervised text tokenizer and detokenizer mainly for Neural Network-based text generation systems where the vocabulary size is predetermined prior to the neural model training."

extra:
  recipe-maintainers:
    - setu4993
    - rluria14
    - ndmaxar
    - oblute
