{% set name = "sentencepiece" %}
{% set version = "0.1.95" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sentencepiece-{{ version }}.tar.gz
  sha256: 8dd6e3e110f4c3f85a46e4a2ae1b6f7cf020b907fab50eac22beccf1680e0ea5

build:
  number: 5
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - sentencepiece/__init__
    - sentencepiece/sentencepiece_model_pb2
    - sentencepiece/sentencepiece_pb2
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/google/sentencepiece
  summary: SentencePiece is an unsupervised text tokenizer and detokenizer mainly for Neural Network-based text generation systems where the vocabulary size is predetermined prior to the neural model training.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - setu4993
    - rluria14
    - ndmaxar
    - oblute
